### ISSUE TITLE
Merge column in markdown table

### ISSUE THREAD

**Issue by fhoces** [BITSS/ACRE#4]
Hi @joelferg  (testing issues for the first time!)
Can you figure out a way to merge some cells in this column? 
https://github.com/BITSS/ACRE/blob/67050e73c0f3d27efd7587749e6c3205b6c2389a/book/01-intro.Rmd#L11

I am thinking of the "improvements" column (both for the title of col and last cell)
This SO might be useful:
https://stackoverflow.com/questions/23571724/github-markdown-colspan

**Comment by joelferg** [comment]
Hey @fhoces 

It looks like combined cells isn't supported by markdown style tables. You can do it with HTML tables though:

<table><thead><tr><th>Scoping</th><th>Assessment</th><th colspan=2>Improvement</th><th>Robustness</th><th>Extension</th></tr></thead><tbody><tr><td>TEST</td><td>TEST</td><td>TEST</td><td>TEST</td><td>TEST</td><td>TEST</td></tr></tbody></table>

I've made sure the reference/link stuff goes through, so I'll remake the table in HTML on the branch I've made and then push it.

-Joel

**Comment by fhoces** [comment]
Looks great!
Thanks @joelferg!
