### ISSUE TITLE
Assessment chapter updates

### ISSUE THREAD

**Issue by abogdanoski** [BITSS/ACRE#91]
- [x] Introduction: Replace “output” with “display item”
- [x] Remove Survey 2 references
- [x] 2.1: Add definitions for raw vs. analytic data in addition to cleaning and analysis code
- [x] 2.1.1: Delete reference to the “standardized spreadsheet” and required structure; explain that this is part of the survey and each line is a data source @fhoces
- [x] 2.1.2: same as 2.1.1 @fhoces
- [x] 2.1.3: same as 2.1.1@fhoces
- [x] 2.2: replace output-to-be-reproduced with relevant unit of analysis @fhoces
- [x] 2.2.1: replace “ACRE Diagram Builder” -> diagram builder @fhoces
- [x] 2.2.2: verify that the workflow for incomplete diagrams is still the same, especially when the diagram needs to be edited manually (the survey isn’t super clear here and it just points to this section) @fhoces
- [x] 2.2.2: Remove reference to the spreadsheets + Make a reference to examples in Ch. 7
- [x] 2.3: replace “output” with “display item”
- [x] 2.3.1: remove reference to Survey 1 (this step is automatically incorporated into the survey workflow now in Step 0)
- [x] Table 3.1: Raw data information in the Guide doesn't have the same columns as the platform. @fhoces please update it to match.
- [x] Add instructions on what it means to check the "Provided/Cited" columns. @fhoces please review whether my draft is correct.
- [x] @fhoces please draft a section (place it before Assess display items) corresponding to the 3.Master script step on the platform.
- [x] @fhoces Add to 3.1.3.1 Common mistakes “If tree shows multiple files as one input, make sure to separate them with a semicolon (;).” or something to this effect

**Comment by fhoces** [comment]
Building a section for master script is tricky, as it is a "filter" section. I would say that sections 3 and 4 of assessment in the platform, currently match section 3  in the guides, without a clear way to make a one to one mapping.
