### ISSUE TITLE
Definitions to revise 

### ISSUE THREAD

**Issue by abogdanoski** [BITSS/ACRE#93]
- [x] Claim 
Is causal vs descriptive the only categorization of claims?
Alternative definition (from RepliCATs): “A research claim is a single major finding from a published study (for example, a journal article), as well as details of the methods and results that support this finding. A research claim is not equivalent to an entire article. Sometimes the claim as described in the abstract does not exactly match the claim that is tested. In this case, you should consider the research claim to be that which is described in the inferential test, as the next stage of SCORE will focus on testing the replicability of the test results only.”
- [x] Coding error - remove leftover comment “[Aleks/Fernando]” + remove “ACRE procedure”
- [x] Disclosure -- this sounds like transparent reporting but is called “disclosure”; can you confirm that “disclosure” is the most appropriate term to define here?
- [x] Literate programming - replace “best practice”-> reproducibility practice
- [x] Researcher degrees of freedom -- consider extending this definition
- [x] Reproduction package - remove “ At this point you are only assessing the existence of one (or more) reproduction packages, you will not be assessing the quality of its content at this stage.”
- [x] Analysis code – move from 10.2 to 10.1
- [x] Display item

**Comment by fhoces** [comment]
confirm that disclosure refers to showing all tests in this context. The term comes Ted's paper on research transparency principles (science 2014)
