### ISSUE TITLE
Concluding the Reproduction chapter updates

### ISSUE THREAD

**Issue by abogdanoski** [BITSS/ACRE#97]
- [x] Introduction: “If you wish to modify your reproduction after submitting it, you will have to record *a new reproduction attempt* on the platform and link to the previously completed reproduction.” Sounds right for now, but do we want to make it easy to copy an old reproduction? If so, should this be included in the Guide? @fhoces 
*5.1*
- [x] Line 11: Aleks left two questions here about reproduction package size and referencing original files if don’t have permission to share: "If your new reproduction package is larger than 2Gb (?)[A: how is this determined, it sounds arbitrary?], or it contains data that you don’t have permissions to share, remove the specific files from your reproduction package and add a reference to the original reproduction package [A: what does making a reference mean and look like in this context? I suggest providing an example of how to do that.].” 1. Download the repository 2. Access and give relative path or 1. Go to website, download/obtain data 2. deposit that data in your own package @fhoces 
- [x] Line 13: Indent more
- [x] Lines 15, 16: Should these be greyed out?
- [x] Line 19: Reproduction reports – I think the final language here will depend on the privacy/sharing options. We’ll also need to state who these are sharable with. @fhoces Lets make sure this works with our anonymity/sharing options.
*Anonymity and data sharing:*
- [x] Line 31: Select and update embargo period; suggested language for separating identifiable data from unidentifiable @fhoces Please review the language I suggested here.
- [x] Line 33: Update to reflect anonymity/privacy decisions

**Comment by fhoces** [comment]
Done. One issue that we still need to discuss is how are we going to share the SSRP data ourselves. I propose: 
Monthly or quarterly data dumps, with the first 6 months with no dumps for us to get time to look at the data and come up with some papers. If Ted and Lars agree I would like to put some text in this chapter and the platform saying something like "Starting on date XYZ the SSRP will generate monthly/quarterly data dumps for everybody to use"

**Comment by fhoces** [comment]
@abogdanoski see #a98d583529897850d7e70d8976e0f9b1b90dbc6f

**Comment by abogdanoski** [comment]
Sounds good, I'll bring that up at one of the future meetings. 
IMO, we don't need to tie ourselves to a specific date. It could also be a certain number of reproductions
