### ISSUE TITLE
Communications guidance

### ISSUE THREAD

**Issue by abogdanoski** [BITSS/ACRE#99]
- [x] General - Make language re: SSRP/BITSS consistent throughout: “the [Social Science Reproduction Platform](https://www.socialsciencereproduction.org/) (SSRP), an open-source repository for the results of verifications of computational reproducibility of published work in the social sciences. SSRP is hosted by the [Berkeley Initiative for Transparency in the Social Sciences)](https://www.bitss.org/).”

*Introduction*
- [x] Add a sentence on checking SSRP for previous contact/not over-burdening authors. Maybe also add a sentence on how instructors/advisors can supervise or moderate this process.
- [x] Add a sentence on how long this process might take, and when reproducers should plan to start
- [x] 1.c. (Line 0): Provide more guidance on what “how far” means (“...how “far” your results must deviate from the original work before claiming that the study could not be reproduced.”) Or rephrase away from "could not be reproduced" toward referencing the scale and specific missing items? @fhoces which did you mean here?

*For Reproducers*
- [x] 1. (Line 31): add information for other social science disciplines (might just be AJPS). Doesn't seem relevant anymore (@abogdanoski Did you edit this section?)
- [x] 5. (Line 46): Clarify where to record interactions on the platform
- [x] Contacting the original author to share the results of your reproduction exercise template:
- [x] Line 207: Remove “extensions” as step iv?
Lines 208-214: The `` didn’t do what they’re supposed to. Not sure what the right syntax is here

*For authors*
disciplines (might just be AJPS).
- [x] remove “>” formatting/typing glitch throughout the template letters
disciplines (might just be AJPS).
- [x] depending on the role of instructors per the anonymity solution, we may need to add a note about how to respond to instructors who reach out on behalf of a class. I’m not sure exactly what the specifics of talking to instructors vs. reproducers directly are. @fhoces I think we can leave this for now since I don't think Ted will do this, but we should ask instructors interested in the next phase how they want to do this.

*Harassment/discrimination*
- [x] Add language for other disciplines
- [x] Line 321: Can a non-economist join the AEA to file a complaint?
- [x] Line 333: I added a sentence in the mental health section to clarify that bullying, discrimination, and harassment are not the victim’s fault (original sentence could be triggering)

**Comment by khoeberling** [comment]
We've addressed most of these. @fhoces we left a couple open questions for you.

We should also flag for the next phase to think about how instructors may want to interact with authors (or not) or coordinating asks.
